repos:
  # General pre-commit hooks for common issues
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0  # Version of the hooks
    hooks:
      - id: trailing-whitespace  # Removes trailing whitespaces in files
      - id: end-of-file-fixer  # Ensures files end with a newline
      - id: check-yaml  # Validates YAML file syntax
      - id: check-json  # Validates JSON file syntax

  # Black formatter for consistent code formatting
  - repo: https://github.com/psf/black
    rev: 24.10.0  # Version of Black
    hooks:
      - id: black
        args: ["--line-length", "150"]  # Override default line length to match your preference
        exclude: "tests/.*|docs/.*"  # Skip formatting for files in `tests` or `docs` folders

  # Flake8 for linting Python code
  - repo: https://github.com/PyCQA/flake8
    rev: 7.1.1  # Version of Flake8
    hooks:
      - id: flake8
        args: ["--max-line-length=120"]  # Align line length with Black
        additional_dependencies: ["flake8-bugbear"]  # Add extra linting features

  # Isort for organizing imports
  - repo: https://github.com/pre-commit/mirrors-isort
    rev: v5.10.1  # Version of isort
    hooks:
      - id: isort
        args: ["--profile", "black"]  # Use Black-compatible sorting rules
