[tool.black]
line-length = 120  # Adjust line length to avoid unnecessary line breaks
skip-string-normalization = true  # Preserve single/double quotes as written

[tool.isort]
profile = "black"  # Align isort's formatting with Black to prevent conflicts
line_length = 120  # Keep consistent line length with Black
combine_as_imports = true  # Combine `import x as y` statements into one line when possible
force_sort_within_sections = true  # Always sort imports within categories
