# Dictionary of column synonyms to standardize naming conventions
SYNONYMS = {
    "first_name": ["first name", "given name", "fname", "forename", "christian name", "first", "firstname"],
    "last_name": ["last name", "surname", "family name", "lname", "lastname", "maiden name"],
    "full_name": ["full name", "complete name", "name", "fullname", "legal name", "display name"],
    "age": ["age", "years old", "dob (year)", "age (years)", "customer age", "patient age"],
    "email": ["email", "email address", "e-mail", "user email", "electronic mail", "mail", "email id", "primary email"],
    "phone": [
        "phone number",
        "phone",
        "mobile",
        "cell",
        "contact number",
        "telephone",
        "tel",
        "mobile no",
        "cell number",
        "primary phone",
        "work phone",
        "home phone",
    ],
    "address": [
        "address",
        "street address",
        "mailing address",
        "residence",
        "addr",
        "address line 1",
        "home address",
        "location address",
        "physical address",
        "street",
    ],
    "city": ["city", "town", "location", "municipality", "district", "urban area", "city name"],
    "state": ["state", "province", "region", "territory", "state/province", "st", "administrative area"],
    "postal_code": [
        "postal code",
        "zip code",
        "zip",
        "postcode",
        "post code",
        "pin code",
        "pincode",
        "area code",
        "postal",
    ],
    "gender": ["gender", "sex", "identity", "gender identity", "biological sex", "m/f"],
    "company": [
        "company",
        "employer",
        "business name",
        "organization",
        "firm",
        "corporation",
        "workplace",
        "enterprise",
        "org",
        "company name",
    ],
    "country": ["country", "nation", "nationality", "country name", "country of residence", "country code"],
    "dob": ["dob", "birthdate", "birthday", "date of birth", "birth date", "birth day", "born on", "birth"],
    "department": ["department", "dept", "division", "unit", "branch", "section", "team", "functional area", "group"],
    "job_title": [
        "job title",
        "position",
        "occupation",
        "role",
        "job position",
        "designation",
        "job function",
        "title",
        "job role",
        "employment title",
        "job name",
    ],
    "marital_status": [
        "marital status",
        "family status",
        "relationship status",
        "civil status",
        "marriage status",
        "matrimonial status",
    ],
    "username": [
        "username",
        "login name",
        "user id",
        "userid",
        "login id",
        "screen name",
        "handle",
        "alias",
        "user",
        "login",
    ],
    "id": [
        "id",
        "identifier",
        "record id",
        "unique id",
        "customer id",
        "primary key",
        "pk",
        "employee id",
        "account number",
        "reference number",
        "membership id",
        "uid",
        "number",
    ],
    "nickname": [
        "nickname",
        "alias",
        "preferred name",
        "nick",
        "known as",
        "pet name",
        "informal name",
        "moniker",
        "sobriquet",
    ],
    "profile_picture": [
        "profile picture",
        "avatar",
        "photo",
        "image",
        "profile photo",
        "profile image",
        "display picture",
        "portrait",
        "headshot",
        "user image",
        "profile pic",
        "dp",
    ],
    "website": [
        "website",
        "webpage",
        "homepage",
        "URL",
        "web address",
        "site",
        "domain",
        "web page",
        "online presence",
        "internet address",
        "site url",
        "web url",
    ],
    "ssn": [
        "ssn",
        "social security number",
        "social security",
        "social security no",
        "ss#",
        "social insurance number",
        "social insurance",
        "sin",
        "national insurance number",
        "nin",
        "nino",
    ],
    "tax_id": [
        "tax id",
        "tax identifier",
        "TIN",
        "tax number",
        "tax file number",
        "tfn",
        "taxpayer identification number",
        "irs number",
        "vat number",
        "tax registration number",
        "tax reference",
    ],
    "salary": [
        "salary",
        "income",
        "wage",
        "pay",
        "compensation",
        "earnings",
        "remuneration",
        "annual salary",
        "monthly salary",
        "stipend",
        "base pay",
        "gross salary",
        "net salary",
        "take home",
    ],
    "employee_id": [
        "employee id",
        "emp id",
        "staff id",
        "personnel id",
        "worker id",
        "badge number",
        "employee number",
        "staff number",
        "payroll id",
        "emp no",
        "employment id",
    ],
    "manager": [
        "manager",
        "supervisor",
        "boss",
        "team lead",
        "team leader",
        "line manager",
        "reporting manager",
        "direct supervisor",
        "head",
        "superior",
        "management contact",
    ],
    "education": [
        "education",
        "educational background",
        "qualification",
        "academic background",
        "schooling",
        "academic history",
        "academic qualification",
        "educational qualification",
        "studies",
    ],
    "degree": [
        "degree",
        "qualification",
        "education level",
        "academic degree",
        "diploma",
        "certificate",
        "academic qualification",
        "educational attainment",
        "graduate degree",
        "credential",
    ],
    "experience": [
        "experience",
        "years of experience",
        "work experience",
        "professional experience",
        "job experience",
        "career history",
        "employment history",
        "work history",
        "professional background",
    ],
    "birth_place": [
        "birth place",
        "place of birth",
        "birthplace",
        "born in",
        "city of birth",
        "country of birth",
        "birth location",
        "native place",
        "origin",
        "hometown",
    ],
    "language": [
        "language",
        "spoken language",
        "native language",
        "mother tongue",
        "primary language",
        "language spoken",
        "fluent in",
        "language proficiency",
        "language skills",
        "linguistics",
    ],
    "national_id": [
        "national id",
        "national identifier",
        "id number",
        "identity number",
        "national identity",
        "government id",
        "official id",
        "identity card number",
        "id card number",
        "citizen id",
    ],
    "fax": ["fax", "facsimile", "fax number", "fax no", "facsimile number", "telecopier", "fax machine", "fax line"],
    "notes": [
        "notes",
        "remarks",
        "comments",
        "observations",
        "additional info",
        "additional information",
        "comment",
        "note",
        "description",
        "details",
        "memo",
        "annotation",
        "special notes",
    ],
    "secondary_email": [
        "secondary email",
        "alternate email",
        "backup email",
        "second email",
        "other email",
        "additional email",
        "personal email",
        "work email",
    ],
    "date_joined": [
        "date joined",
        "join date",
        "start date",
        "hiring date",
        "employment date",
        "onboarding date",
        "date of joining",
        "commencement date",
    ],
    "emergency_contact": [
        "emergency contact",
        "emergency contact person",
        "ice contact",
        "next of kin",
        "contact in case of emergency",
        "emergency phone",
        "emergency number",
    ],
    "blood_type": ["blood type", "blood group", "rh factor", "blood", "abo type"],
    "middle_name": ["middle name", "middle", "mid name", "middle initial", "mi", "second name", "middle names"],
    "suffix": [
        "suffix",
        "name suffix",
        "title suffix",
        "generational suffix",
        "name extension",
        "jr",
        "sr",
        "III",
        "IV",
    ],
    "prefix": ["prefix", "title", "honorific", "salutation", "name prefix", "courtesy title", "professional title"],
    "citizenship": [
        "citizenship",
        "nationality",
        "citizen of",
        "citizenship status",
        "legal status",
        "passport country",
    ],
    "passport": ["passport", "passport number", "passport no", "passport id", "travel document", "international id"],
    "license": [
        "license",
        "driver license",
        "driving license",
        "driver's license",
        "license number",
        "dl number",
        "driver license number",
    ],
    "social_media": [
        "social media",
        "social profiles",
        "social handles",
        "social accounts",
        "online profiles",
        "media links",
        "social network",
    ],
    "skills": [
        "skills",
        "abilities",
        "competencies",
        "expertise",
        "qualifications",
        "capabilities",
        "proficiencies",
        "technical skills",
    ],
    "hobbies": [
        "hobbies",
        "interests",
        "pastimes",
        "leisure activities",
        "personal interests",
        "activities",
        "recreation",
    ],
    "status": [
        "status",
        "account status",
        "employment status",
        "active status",
        "current status",
        "profile status",
        "user status",
        "record status",
    ],
    "account_type": [
        "account type",
        "user type",
        "membership type",
        "account level",
        "account category",
        "user category",
        "customer type",
    ],
    "preferred_contact": [
        "preferred contact",
        "contact preference",
        "preferred contact method",
        "contact method",
        "best contact",
        "preferred way to contact",
    ],
    "timezone": [
        "timezone",
        "time zone",
        "local time",
        "time zone offset",
        "tz",
        "local timezone",
        "geographical time",
    ],
    "preferred_language": [
        "preferred language",
        "language preference",
        "communication language",
        "default language",
        "interface language",
    ],
}
